version: "3"

volumes:
  data:

services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.0
    container_name: etcd
    hostname: etcd-host
    environment:
      ETCD_NAME: default
      ETCD_DATA_DIR: "/etcd-data"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_INITIAL_CLUSTER: "default=http://0.0.0.0:2380"
      ETCD_LOGGER: zap
    volumes:
      - data:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"
