version: '3'

services: 
    jaeger:
        image: jaegertracing/all-in-one:1.18
        container_name: jaeger
        hostname: jaeger-host
        environment:
            COLLECTOR_ZIPKIN_HTTP_PORT: 9411
        ports:
            - '5775/udp'    # agent: accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
            - '6831/udp'    # agent: accept jaeger.thrift over compact thrift protocol
            - '6832/udp'    # agent: accept jaeger.thrift over binary thrift protocol
            - '5778'        # agent: serve configs
            - '16686'       # query: serve frontend
            - '14268'       # collector: accept jaeger.thrift directly from clients
            - '14250'       # collector: accept model.proto
            - '9411'        # collector: Zipkin compatible endpoint (optional)
