version: "3"

volumes:
  nameserver_logs:
  broker_logs:
  broker_store:

services:
  nameserver:
    build: .
    container_name: rocketmq_nameserver
    hostname: nameserver-host
    command: sh mqnamesrv
    volumes:
      - nameserver_logs:/home/rocketmq/logs
    ports:
      - 9876:9876

  broker:
    depends_on:
      - nameserver
    build: .
    container_name: rocketmq_broker
    hostname: broker-host
    command: 'sh mqbroker -c ../conf/broker.conf'
    environment:
      NAMESRV_ADDR: nameserver:9876
    volumes:
      - broker_logs:/home/rocketmq/logs
      - broker_store:/home/rocketmq/store
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
