version: "3"

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql-host
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql    # 持久化数据
      - mysql_conf:/etc/mysql/conf.d # 配置文件

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin-host
    environment:
      PMA_HOST: mysql
    ports:
      - "80"
    depends_on:
      - mysql

volumes:
  mysql_data:
  mysql_conf:
