version: "3"

services:

  mysql:
    image: mysql:8
    container_name: mysql
    hostname: mysql-host
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+08:00
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql    # 持久化数据
      - mysql_conf:/etc/mysql/conf.d # 配置文件

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin-host
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql:3306,host.docker.internal:3306
      UPLOAD_LIMIT: 100000000 # 最大上传文件大小设为 100M，放开 SQL 文件导入等场景的文件大小限制
    ports:
      - "3380:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
  mysql_conf:
