version: "3"

volumes:
  data:
  config:
  log:

services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    hostname: postgres-host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin
    hostname: pgadmin-host
    environment:
      PGADMIN_DEFAULT_EMAIL: xvrzhao@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 5480:80
