version: '3'

services:
  redis:
    build: .
    container_name: redis
    hostname: redis-host
    ports:
      - "6379"
    volumes:
      - redis_data:/data      # AOF 数据
      - redis_conf:/etc/redis # 配置

volumes:
  redis_data:
  redis_conf: