version: "3"

volumes:
  prometheus_config:
  prometheus_data:
  grafana_config:
  grafana_data:

services:
  prometheus:
    build: .
    container_name: prometheus
    hostname: prometheus-host
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml # 指定配置文件
      - --web.enable-lifecycle # 运行通过 HTTP 接口重新加载配置
    volumes:
      - prometheus_config:/etc/prometheus # 配置
      - prometheus_data:/prometheus # TSDB、WAL 等数据

  # user: admin, psw: admin
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    hostname: grafana-host
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana_config:/etc/grafana # 配置
      - grafana_data:/var/lib/grafana # DB、Plugins 等数据
