version: "3"

volumes:
  prometheus_config:
  prometheus_data:
  alertmanager_config:
  grafana_config:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    hostname: prometheus-host
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml # 指定配置文件
      - --web.enable-lifecycle # 运行通过 HTTP 接口重新加载配置 (POST localhost:9090/-/reload)
    volumes:
      - prometheus_config:/etc/prometheus # 配置
      - prometheus_data:/prometheus # TSDB、WAL 等数据
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    hostname: alertmanager-host
    ports:
      - 9093:9093
    volumes:
      - alertmanager_config:/etc/alertmanager # 配置

  # user: admin, psw: admin
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    hostname: grafana-host
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana_config:/etc/grafana # 配置
      - grafana_data:/var/lib/grafana # DB、Plugins 等数据
